name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Building jones from the bones-kernel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
#          windows-latest,    # put back once fixed variable length array useage or can use clang
#          macos-13,          # macos-13 is an intel runner
          macos-14,           # macos-14 is apple silicon
        ]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5                         # Used to host cibuildwheel
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.0.1        # 2.23.3

      - name: Install numpy
        run: python -m pip install numpy

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
